### ISSUE TITLE
neo4j及GDS插件版本问题

### ISSUE THREAD

**Issue by dumplingbao** [limafang/tiny-graphrag#1]
你好，启动此工程除了存在一些代码问题，修复后正常，目前向neo4j中写入存在问题，请问版本是不是硬性的要求，我当前的版本是：
neo4j：[5.2.0-community]
GDS：neo4j-graph-data-science-2.4.6.jar
此外，在运行的空的neo4j数据库，提示Entity和Relationship的提示，是否还存在其他的未说明的前置条件
谢谢！

**Comment by limafang** [comment]
@dumplingbao 请严格按照版本运行，因为不同版本的 neo4j 的适配都不同，另外应该没有其他需要的前置条件，如果修改版本后依然存在错误，可以带上截图再看看

**Comment by dumplingbao** [comment]
我已经切换到最新版本，目前运行提示的错误见截图，我发现应该是neo4j图谱数据没有创建成功导致的，提示Entity及属性不存在、Relationship这些是否会自动创建，有没有执行的脚本
<img width="1545" alt="iShot_2024-11-20_11 39 45" src="https://github.com/user-attachments/assets/8dd6eb45-841a-4b82-b73c-7502c6ab4f13">
<img width="993" alt="iShot_2024-11-20_11 40 19" src="https://github.com/user-attachments/assets/cec2b739-a91a-4c0a-949a-345c90ed3372">

**Comment by limafang** [comment]
@dumplingbao 可以试试代码中的query语句在neo4j中能够正常使用吗。另外，我新的 commit 修复了之前 read path 的一些错误如果还有问题，欢迎+我的VX ：Azula_Fire
